#157 - Atualizando estrutura do backlog de produto
fga-eps-mds/2019.1-Grupo-1 pull request #194
Opened 2019-04-23 00:19 UTC by KahCosta

## Tipo da mudança 
- [ ] Resolve Bug 
- [ ] Adiciona nova funcionalidade 
- [x] Atualiza documentação 

Atualização do backlog de produto

#157 
Conecte sua issue abaixo com o GitHub :v:

resolve #157

2019-04-23 02:29 UTC, Lucas362 requested changes
Bom material, só precisa de correção de erros de digitação das IS05, IS12 e IS13

2019-04-25 16:09 UTC, KahCosta commented
Vou refatorar agora mesmo!

2019-04-25 16:20 UTC, Lucas362 submitted a review, later dismissed

2019-04-25 19:25 UTC, Lucas362 commented
Bom trabalho! PR aceito! :trophy:

2019-04-25 19:26 UTC, Lucas362 approved these changes

2019-04-25 19:26 UTC, merged